import { motion } from "framer-motion";
import { Shield, ShieldAlert, Lock, Server, Network, Cloud, FileKey, Eye, Shield2 } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

const solutions = [
  {
    title: "Security Information and Event Management (SIEM)",
    description: "Real-time analysis of security alerts generated by applications and network hardware.",
    icon: ShieldAlert,
    features: [
      "Log Management & Analytics",
      "Real-time Monitoring",
      "Threat Detection",
      "Incident Response",
      "Compliance Reporting",
      "Security Intelligence"
    ]
  },
  {
    title: "Security Orchestration, Automation and Response (SOAR)",
    description: "Streamline security operations and respond to cyber threats with automated workflows.",
    icon: Server,
    features: [
      "Automated Incident Response",
      "Workflow Orchestration",
      "Case Management",
      "Threat Intelligence Integration",
      "Playbook Automation",
      "KPI Reporting"
    ]
  },
  {
    title: "Extended Detection and Response (XDR)",
    description: "Unified security incident detection and response across multiple security layers.",
    icon: Network,
    features: [
      "Cross-layer Detection",
      "Automated Response",
      "Threat Hunting",
      "Behavioral Analytics",
      "Cloud Security",
      "Endpoint Protection"
    ]
  },
  {
    title: "Data Loss Prevention (DLP)",
    description: "Protect sensitive data and prevent unauthorized data exfiltration.",
    icon: FileKey,
    features: [
      "Content Inspection",
      "Policy Enforcement",
      "Data Classification",
      "Email Protection",
      "Endpoint Control",
      "Cloud DLP"
    ]
  },
  {
    title: "Security Access Service Edge (SASE)",
    description: "Cloud-delivered platform that combines network security functions with WAN capabilities.",
    icon: Cloud,
    features: [
      "Zero Trust Access",
      "Cloud Security",
      "SD-WAN Integration",
      "Threat Prevention",
      "Data Protection",
      "Identity Management"
    ]
  },
  {
    title: "Privileged Access Management (PAM)",
    description: "Control, monitor, and secure privileged access to critical assets.",
    icon: Lock,
    features: [
      "Password Vault",
      "Session Recording",
      "Access Workflow",
      "Just-in-Time Access",
      "Audit & Compliance",
      "Secret Management"
    ]
  }
];

export const SecuritySolutions = () => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-8">
      {solutions.map((solution, index) => (
        <motion.div
          key={solution.title}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: index * 0.1 }}
          viewport={{ once: true }}
        >
          <Card className="h-full hover:shadow-lg transition-shadow">
            <CardContent className="p-6">
              <solution.icon className="w-12 h-12 text-[#ea384c] mb-4" />
              <h3 className="text-xl font-semibold mb-2">{solution.title}</h3>
              <p className="text-gray-600 mb-4">{solution.description}</p>
              <ul className="space-y-2">
                {solution.features.map((feature) => (
                  <li key={feature} className="flex items-center text-sm text-gray-600">
                    <div className="w-1.5 h-1.5 bg-[#ea384c] rounded-full mr-2" />
                    {feature}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </motion.div>
      ))}
    </div>
  );
};