import { motion } from "framer-motion";
import { Shield, ShieldAlert, Lock, Server, Network, Cloud } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Footer } from "@/components/Footer";

const solutions = [
  {
    title: "Security Information and Event Management (SIEM)",
    description: "Real-time analysis of security alerts generated by applications and network hardware.",
    icon: ShieldAlert,
    features: [
      "Log Management & Analytics",
      "Real-time Monitoring",
      "Threat Detection",
      "Incident Response",
      "Compliance Reporting",
      "Security Intelligence"
    ]
  },
  {
    title: "Security Orchestration, Automation and Response (SOAR)",
    description: "Streamline security operations and respond to cyber threats with automated workflows.",
    icon: Server,
    features: [
      "Automated Incident Response",
      "Workflow Orchestration",
      "Case Management",
      "Threat Intelligence Integration",
      "Playbook Automation",
      "KPI Reporting"
    ]
  },
  {
    title: "Extended Detection and Response (XDR)",
    description: "Unified security incident detection and response across multiple security layers.",
    icon: Network,
    features: [
      "Cross-layer Detection",
      "Automated Response",
      "Threat Hunting",
      "Behavioral Analytics",
      "Cloud Security",
      "Endpoint Protection"
    ]
  }
];

const partners = [
  {
    name: "Fortinet",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/62/Fortinet_logo.svg",
    description: "Complete security fabric architecture"
  },
  {
    name: "Cisco",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Cisco_logo_blue_2016.svg/2560px-Cisco_logo_blue_2016.svg.png",
    description: "Network security solutions"
  },
  {
    name: "Forcepoint",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Forcepoint_logo.svg",
    description: "Human-centric cybersecurity"
  },
  {
    name: "Trend Micro",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Trend_Micro_logo.svg",
    description: "Hybrid cloud security"
  },
  {
    name: "Check Point",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Check_Point_Software_Technologies_logo.svg/2560px-Check_Point_Software_Technologies_logo.svg.png",
    description: "Advanced threat prevention"
  },
  {
    name: "Palo Alto Networks",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Palo_Alto_Networks_logo.svg/2560px-Palo_Alto_Networks_logo.svg.png",
    description: "Next-generation security"
  },
  {
    name: "Kaspersky",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Kaspersky_Lab_logo.svg/2560px-Kaspersky_Lab_logo.svg.png",
    description: "Endpoint security solutions"
  },
  {
    name: "Ghangor Cloud",
    logo: "/lovable-uploads/e894ef9f-fa46-4132-b8c1-b76e606e7b18.png",
    description: "Cloud security solutions"
  }
];

const Cybersecurity = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="pt-24 pb-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            <div className="flex items-center justify-center gap-4 mb-6">
              <Shield className="w-12 h-12 text-[#ea384c]" />
              <h1 className="text-4xl font-bold text-gray-900">Cybersecurity Solutions</h1>
            </div>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Comprehensive security solutions to protect your digital assets and infrastructure
              with industry-leading technologies and expert implementation.
            </p>
          </motion.div>

          <Tabs defaultValue="solutions" className="mb-16">
            <TabsList className="grid w-full grid-cols-2 max-w-[400px] mx-auto">
              <TabsTrigger value="solutions">Solutions</TabsTrigger>
              <TabsTrigger value="features">Features</TabsTrigger>
            </TabsList>
            <TabsContent value="solutions">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-8">
                {solutions.map((solution, index) => (
                  <motion.div
                    key={solution.title}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                  >
                    <Card className="h-full hover:shadow-lg transition-shadow">
                      <CardContent className="p-6">
                        <solution.icon className="w-12 h-12 text-[#ea384c] mb-4" />
                        <h3 className="text-xl font-semibold mb-2">{solution.title}</h3>
                        <p className="text-gray-600 mb-4">{solution.description}</p>
                        <ul className="space-y-2">
                          {solution.features.map((feature) => (
                            <li key={feature} className="flex items-center text-sm text-gray-600">
                              <div className="w-1.5 h-1.5 bg-[#ea384c] rounded-full mr-2" />
                              {feature}
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </div>
            </TabsContent>
            <TabsContent value="features">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
                <Card className="h-full">
                  <CardContent className="p-6">
                    <h3 className="text-xl font-semibold mb-4">Threat Protection</h3>
                    <ul className="space-y-3">
                      <li className="flex items-center">
                        <Lock className="w-5 h-5 text-[#ea384c] mr-2" />
                        <span>Advanced Threat Prevention</span>
                      </li>
                      <li className="flex items-center">
                        <Shield className="w-5 h-5 text-[#ea384c] mr-2" />
                        <span>Zero-Day Attack Protection</span>
                      </li>
                      <li className="flex items-center">
                        <Cloud className="w-5 h-5 text-[#ea384c] mr-2" />
                        <span>Cloud Security Posture Management</span>
                      </li>
                    </ul>
                  </CardContent>
                </Card>
                <Card className="h-full">
                  <CardContent className="p-6">
                    <h3 className="text-xl font-semibold mb-4">Security Services</h3>
                    <ul className="space-y-3">
                      <li className="flex items-center">
                        <Server className="w-5 h-5 text-[#ea384c] mr-2" />
                        <span>24/7 Security Operations Center</span>
                      </li>
                      <li className="flex items-center">
                        <Network className="w-5 h-5 text-[#ea384c] mr-2" />
                        <span>Incident Response Team</span>
                      </li>
                      <li className="flex items-center">
                        <ShieldAlert className="w-5 h-5 text-[#ea384c] mr-2" />
                        <span>Vulnerability Assessment</span>
                      </li>
                    </ul>
                  </CardContent>
                </Card>
              </div>
            </TabsContent>
          </Tabs>

          <section className="mb-16">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="text-center mb-12"
            >
              <h2 className="text-3xl font-bold text-gray-900 mb-4">Our Technology Partners</h2>
              <p className="text-lg text-gray-600">
                We partner with world-class security providers to deliver comprehensive cybersecurity solutions
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {partners.map((partner, index) => (
                <motion.div
                  key={partner.name}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  viewport={{ once: true }}
                >
                  <Card className="h-full hover:shadow-lg transition-shadow">
                    <CardContent className="p-6">
                      <div className="aspect-[3/1] relative mb-4 bg-white rounded-lg overflow-hidden p-4 flex items-center justify-center">
                        <img
                          src={partner.logo}
                          alt={`${partner.name} logo`}
                          className="object-contain w-full h-full"
                        />
                      </div>
                      <h3 className="text-xl font-semibold mb-2">{partner.name}</h3>
                      <p className="text-gray-600">{partner.description}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Cybersecurity;